### ISSUE TITLE
Update for newest Handlebar AST

### ISSUE THREAD

**Issue by alexturpin** [zeppelin/handlebars-serializer#2]
The Handlebar AST has been updated and this no longer does anything on an AST generated with Handlebar 4+.

**Comment by zeppelin** [comment]
@alexturpin sorry, I don't use this anymore :(

If you're willing to take a stab at supporting recent Handlebars versions, go for it, PRs accepted! ;)

**Comment by alexturpin** [comment]
No worry at all, just wanted to check in case! For now I've implemented a very limited version just to cover my needs, but should I make it more complete I'll be sure to send a PR.

**Comment by pinturic** [comment]
@alexturpin do you still have the serializer with version 4 ?
